type operator = {
  modulatedBy: number[],
  feedbackFrom?: number,

  // grid position (units) in the diagram
  x: number, // from left
  y: number, // from bottom
};

export type algorithm = {[key: number]: operator};

export const algorithms : {[key: number]: algorithm} = {
  1: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [5], x: 1, y: 1},
      5: {modulatedBy: [6], x: 1, y: 2},
      6: {modulatedBy: [], x: 1, y: 3, feedbackFrom: 6}},
  2: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 2},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [5], x: 1, y: 1},
      5: {modulatedBy: [6], x: 1, y: 2},
      6: {modulatedBy: [], x: 1, y: 3}},
  3: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [3], x: 0, y: 1},
      3: {modulatedBy: [], x: 0, y: 2},
      4: {modulatedBy: [5], x: 1, y: 0},
      5: {modulatedBy: [6], x: 1, y: 1},
      6: {modulatedBy: [], x: 1, y: 2, feedbackFrom: 6}},
  4: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [3], x: 0, y: 1},
      3: {modulatedBy: [], x: 0, y: 2},
      4: {modulatedBy: [5], x: 1, y: 0},
      5: {modulatedBy: [6], x: 1, y: 1},
      6: {modulatedBy: [], x: 1, y: 2, feedbackFrom: 4}},
  5: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [], x: 1, y: 1},
      5: {modulatedBy: [6], x: 2, y: 0},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 6}},
  6: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [], x: 1, y: 1},
      5: {modulatedBy: [6], x: 2, y: 0},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 5}},
  7: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4,5], x: 1, y: 0},
      4: {modulatedBy: [], x: 1, y: 1},
      5: {modulatedBy: [6], x: 2, y: 1},
      6: {modulatedBy: [], x: 2, y: 2, feedbackFrom: 6}},
  8: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4,5], x: 1, y: 0},
      4: {modulatedBy: [], x: 1, y: 1, feedbackFrom: 4},
      5: {modulatedBy: [6], x: 2, y: 1},
      6: {modulatedBy: [], x: 2, y: 2}},
  9: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 2},
      3: {modulatedBy: [4,5], x: 1, y: 0},
      4: {modulatedBy: [], x: 1, y: 1},
      5: {modulatedBy: [6], x: 2, y: 1},
      6: {modulatedBy: [], x: 2, y: 2}},
  10: {
      1: {modulatedBy: [2], x: 2, y: 0},
      2: {modulatedBy: [3], x: 2, y: 1},
      3: {modulatedBy: [], x: 2, y: 2, feedbackFrom: 3},
      4: {modulatedBy: [5,6], x: 1, y: 0},
      5: {modulatedBy: [], x: 0, y: 1},
      6: {modulatedBy: [], x: 1, y: 1}},
  11: {
      1: {modulatedBy: [2], x: 2, y: 0},
      2: {modulatedBy: [3], x: 2, y: 1},
      3: {modulatedBy: [], x: 2, y: 2},
      4: {modulatedBy: [5,6], x: 1, y: 0},
      5: {modulatedBy: [], x: 0, y: 1},
      6: {modulatedBy: [], x: 1, y: 1, feedbackFrom: 6}},
  12: {
      1: {modulatedBy: [2], x: 3, y: 0},
      2: {modulatedBy: [], x: 3, y: 1},
      3: {modulatedBy: [4,5,6], x: 1, y: 0},
      4: {modulatedBy: [], x: 0, y: 1},
      5: {modulatedBy: [], x: 1, y: 1},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 6}},
  13: {
      3: {modulatedBy: [4,5,6], x: 1, y: 0},
      4: {modulatedBy: [], x: 0, y: 1},
      5: {modulatedBy: [], x: 1, y: 1},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 6},
      1: {modulatedBy: [2], x: 3, y: 0},
      2: {modulatedBy: [], x: 3, y: 1}},  
  14: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [5,6], x: 1, y: 1},
      5: {modulatedBy: [], x: 0, y: 2},
      6: {modulatedBy: [], x: 1, y: 2, feedbackFrom: 6}},
  15: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 2},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [5,6], x: 1, y: 1},
      5: {modulatedBy: [], x: 0, y: 2},
      6: {modulatedBy: [], x: 1, y: 2, feedbackFrom: 6}},
  16: {
      1: {modulatedBy: [2,3,5], x: 1, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 1},
      4: {modulatedBy: [], x: 1, y: 2},
      5: {modulatedBy: [6], x: 2, y: 1},
      6: {modulatedBy: [], x: 2, y: 2, feedbackFrom: 6}},
  17: {
      1: {modulatedBy: [2,3,5], x: 1, y: 0},
      2: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 2},
      3: {modulatedBy: [4], x: 1, y: 1},
      4: {modulatedBy: [], x: 1, y: 2},
      5: {modulatedBy: [6], x: 2, y: 1},
      6: {modulatedBy: [], x: 2, y: 2}},
  18: {
      1: {modulatedBy: [2,3,4], x: 1, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [], x: 1, y: 1, feedbackFrom: 3},
      4: {modulatedBy: [5], x: 2, y: 1},
      5: {modulatedBy: [6], x: 2, y: 2},
      6: {modulatedBy: [], x: 2, y: 3}},
  19: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [3], x: 0, y: 1},
      3: {modulatedBy: [], x: 0, y: 2},
      4: {modulatedBy: [6], x: 1, y: 0},
      5: {modulatedBy: [6], x: 2, y: 0},
      6: {modulatedBy: [], x: 1, y: 1, feedbackFrom: 6}},
  20: {
      1: {modulatedBy: [3], x: 0, y: 0},
      2: {modulatedBy: [3], x: 1, y: 0},
      3: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 3},
      4: {modulatedBy: [5,6], x: 2, y: 0},
      5: {modulatedBy: [], x: 1, y: 1},
      6: {modulatedBy: [], x: 2, y: 1}},
  21: {
      1: {modulatedBy: [3], x: 0, y: 0},
      2: {modulatedBy: [3], x: 1, y: 0},
      3: {modulatedBy: [], x: 0, y: 1, feedbackFrom: 3},
      4: {modulatedBy: [6], x: 2, y: 0},
      5: {modulatedBy: [6], x: 3, y: 0},
      6: {modulatedBy: [], x: 2, y: 1}},
  22: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [6], x: 1, y: 0},
      4: {modulatedBy: [6], x: 2, y: 0},
      5: {modulatedBy: [6], x: 3, y: 0},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 6}},
  23: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [3], x: 1, y: 0},
      3: {modulatedBy: [], x: 1, y: 1},
      4: {modulatedBy: [6], x: 2, y: 0},
      5: {modulatedBy: [6], x: 3, y: 0},
      6: {modulatedBy: [], x: 2, y: 1, feedbackFrom: 6}},
  24: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [6], x: 2, y: 0},
      4: {modulatedBy: [6], x: 3, y: 0},
      5: {modulatedBy: [6], x: 4, y: 0},
      6: {modulatedBy: [], x: 3, y: 1, feedbackFrom: 6}},
  25: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [], x: 2, y: 0},
      4: {modulatedBy: [6], x: 3, y: 0},
      5: {modulatedBy: [6], x: 4, y: 0},
      6: {modulatedBy: [], x: 3, y: 1, feedbackFrom: 6}},
  26: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [3], x: 1, y: 0},
      3: {modulatedBy: [], x: 1, y: 1},
      4: {modulatedBy: [5,6], x: 3, y: 0},
      5: {modulatedBy: [], x: 2, y: 1},
      6: {modulatedBy: [], x: 3, y: 1, feedbackFrom: 6}},
  27: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [3], x: 1, y: 0},
      3: {modulatedBy: [], x: 1, y: 1, feedbackFrom: 3},
      4: {modulatedBy: [5,6], x: 3, y: 0},
      5: {modulatedBy: [], x: 2, y: 1},
      6: {modulatedBy: [], x: 3, y: 1}},
  28: {
      1: {modulatedBy: [2], x: 0, y: 0},
      2: {modulatedBy: [], x: 0, y: 1},
      3: {modulatedBy: [4], x: 1, y: 0},
      4: {modulatedBy: [5], x: 1, y: 1},
      5: {modulatedBy: [], x: 1, y: 2, feedbackFrom: 5},
      6: {modulatedBy: [], x: 2, y: 0}},
  29: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [4], x: 2, y: 0},
      4: {modulatedBy: [], x: 2, y: 1},
      5: {modulatedBy: [6], x: 3, y: 0},
      6: {modulatedBy: [], x: 3, y: 1, feedbackFrom: 6}},
  30: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [4], x: 2, y: 0},
      4: {modulatedBy: [5], x: 2, y: 1},
      5: {modulatedBy: [], x: 2, y: 2, feedbackFrom: 5},
      6: {modulatedBy: [], x: 3, y: 0}},
  31: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [], x: 2, y: 0},
      4: {modulatedBy: [], x: 3, y: 0},
      5: {modulatedBy: [6], x: 4, y: 0},
      6: {modulatedBy: [], x: 4, y: 1, feedbackFrom: 6}},
  32: {
      1: {modulatedBy: [], x: 0, y: 0},
      2: {modulatedBy: [], x: 1, y: 0},
      3: {modulatedBy: [], x: 2, y: 0},
      4: {modulatedBy: [], x: 3, y: 0},
      5: {modulatedBy: [], x: 4, y: 0},
      6: {modulatedBy: [], x: 5, y: 0, feedbackFrom: 6}},
};